FROM python:3.10.5-slim-bullseye

# Install Python runtime dependencies
COPY requirements.txt /tmp/
RUN pip install -r /tmp/requirements.txt

# # Install application
WORKDIR /app
COPY pyproject.toml ./
COPY src/ src/
RUN pip install .

ENTRYPOINT ["mycli"]
